import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:geolocator/geolocator.dart';
import 'package:geolocator_platform_interface/geolocator_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:ride_tracker_1/main.dart';
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';
import 'package:integration_test/integration_test.dart';

class MockGeolocator extends GeolocatorPlatform
    with MockPlatformInterfaceMixin {
  final StreamController<Position> _positionStreamController =
      StreamController<Position>.broadcast();

  @override
  Future<LocationPermission> checkPermission() async =>
      LocationPermission.always;

  @override
  Future<LocationPermission> requestPermission() async =>
      LocationPermission.always;

  @override
  Stream<Position> getPositionStream({LocationSettings? locationSettings}) {
    return _positionStreamController.stream;
  }

  void yieldPosition(Position position) {
    _positionStreamController.add(position);
  }
}

class MockPathProvider extends PathProviderPlatform
    with MockPlatformInterfaceMixin {
  @override
  Future<String?> getApplicationDocumentsPath() async {
    return '.';
  }
}

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  setUpAll(() {
    HttpOverrides.global = null;
  });

  testWidgets('Ride Tracking logs and path creation test on UI',
      (WidgetTester tester) async {
    final mockGeo = MockGeolocator();
    GeolocatorPlatform.instance = mockGeo;
    PathProviderPlatform.instance = MockPathProvider();

    await tester.pumpWidget(const MaterialApp(home: MainNavigation()));

    await tester.pumpAndSettle();

    // The button must be "START NEW RIDE"
    expect(find.text("START NEW RIDE"), findsOneWidget);

    // Start the ride
    await tester.tap(find.text("START NEW RIDE"));
    await tester.pump();

    // Verify button turned to "FINISH SESSION"
    expect(find.text("FINISH SESSION"), findsOneWidget);

    // Yield coordinate 1
    mockGeo.yieldPosition(Position(
      longitude: 73.8567,
      latitude: 18.5204,
      timestamp: DateTime.now(),
      accuracy: 1.0,
      altitude: 0.0,
      altitudeAccuracy: 0.0,
      heading: 0.0,
      headingAccuracy: 0.0,
      speed: 10.0,
      speedAccuracy: 0.0,
    ));
    await tester.pump(const Duration(seconds: 1));

    // Yield coordinate 2
    mockGeo.yieldPosition(Position(
      longitude: 73.8570,
      latitude: 18.5210,
      timestamp: DateTime.now(),
      accuracy: 1.0,
      altitude: 0.0,
      altitudeAccuracy: 0.0,
      heading: 0.0,
      headingAccuracy: 0.0,
      speed: 15.0,
      speedAccuracy: 0.0,
    ));
    await tester.pump(const Duration(seconds: 1));

    await tester.pumpAndSettle();

    // Verify mapping calculations in the UI
    expect(find.text('54.0'), findsOneWidget); // 15.0 * 3.6

    // Finish session
    await tester.tap(find.text("FINISH SESSION"));

    // Wait for file creation processing to finish
    // Replacing pumpAndSettle with pump loop based on the state variable 'START NEW RIDE' returning
    for (int i = 0; i < 50; i++) {
      await tester.pump(const Duration(milliseconds: 100));
      if (find.text("START NEW RIDE").evaluate().isNotEmpty) {
        break;
      }
    }

    expect(find.text("START NEW RIDE"), findsOneWidget);

    // Open logs view to see the list updated
    await tester.tap(find.byIcon(Icons.history));
    await tester.pumpAndSettle();

    // Because the view now updates on logs view, we expect to find "54.0 km/h" in the log
    expect(find.textContaining('54.0 km/h'), findsOneWidget);

    // Clean up local json files generated by this test
    var dir = Directory('.');
    var files = dir
        .listSync()
        .where((f) => f.path.contains('ride_') && f.path.endsWith('.json'))
        .toList();
    for (var f in files) {
      if (f is File) await f.delete();
    }
  });
}
